### PR TITLE
Add support for months, years and days of month

### PR DESCRIPTION
**Pull request by dodoknight**

### CODE REVIEW

**Comment by florent37** [comment]
wow I'm impressed
I will try it and merge it as soon i validate it ;) 

and publish a new release

**Comment by florent37** [comment]
can you just update the README please ?

**Comment by dodoknight** [comment]
Sure. I will try to do it till Friday.

**Comment by dodoknight** [comment]
Updated!

**Comment by florent37** [comment]
I tried to launch it but it throws illegal exceptions
can you update them ?

**Comment by dodoknight** [comment]
Hi ... I tried it on my device and it works... It hadn't been working till I fixed one issue I committed 5 days ago.

**Comment by florent37** [comment]
merged, i push a new release

**Pull request merged**
