### PR TITLE
Fix date picker doesn't resolve date correctly

### PR DESCRIPTION
**Pull request by ralphevmanzano**
Fixed issue raised in issue [257](https://github.com/florent37/SingleDateAndTimePicker/issues/257). Closed the previous PR since it was on master branch

### CODE REVIEW

**Comment by arberg** [comment]
I have reproduced the Today problem, and verified this fixes it. I have merged your changes into my branch, along with all the other pending changes to Florents original 'fork', along with some of my own changes + extensions. Thx for the fix.

https://github.com/arberg/SingleDateAndTimePicker

**Comment by G00fY2** [comment]
Obsolete if #267 gets merged.

**Comment by ralphevmanzano** [comment]
will close this PR as @arberg merged the fixes in #267 already

**Comment by florent37** [comment]
the  #267 has been merged and a new version is available !

**Pull request closed without merging**
