### PR TITLE
Handling of leap dates.

### PR DESCRIPTION
**Pull request by zsoltlengyelit**
WheelDayPicker stores the exact Date of the labels so formatter is not forced to guess the year (wrongly)

### CODE REVIEW

**Comment by Yennefer** [comment]
@florent37 Will this changes be merged? I have the same problem when choosing February 29th in the picker

**Comment by markspit93** [comment]
Thanks a lot for trying to fix this annoying bug.
Are you aware that the sample app crashes on startup?
I am having trouble making it work even after fixing the first error.

**Comment by florent37** [comment]
thanks I merge it

**Comment by Tgo1014** [comment]
I'm having the same issue, selecting Feb, 29  makes it return March, 1st.

**Comment by greensopinion** [comment]
> I can see you changes, but there's a bug in it. When selecting 29-2-2020 (it's a leap date) it converts it into March 1st, when you select the leap date. Can you have a look?

See issue #254

**Pull request merged**
