### PR TITLE
Fix crash when default date has 31th day

### LINKED ISSUE #164: Crash if today is the 31th
When using the month picker, it crashes if today is the 31th. I saw this happening on August 31th.

I will try to fix it and do a pull request. :)

Here is the crash log though:

> 08-31 04:00:50.436 4266-4266/com.laudien.p1xelfehler.x E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.laudien.p1xelfehler.x, PID: 4266
    java.lang.IndexOutOfBoundsException: Index: 30, Size: 30
        at java.util.ArrayList.get(ArrayList.java:411)
        at com.github.florent37.singledateandtimepicker.widget.WheelPicker.setDefaultDate(WheelPicker.java:256)
        at com.github.florent37.singledateandtimepicker.SingleDateAndTimePicker.setDefaultDate(SingleDateAndTimePicker.java:459)
        at com.github.florent37.singledateandtimepicker.SingleDateAndTimePicker.onAttachedToWindow(SingleDateAndTimePicker.java:218)
        at android.view.View.dispatchAttachedToWindow(View.java:15391)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2953)
        at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:2960)
        at android.view.ViewGroup.addViewInner(ViewGroup.java:4493)
        at android.view.ViewGroup.addView(ViewGroup.java:4295)
        at android.support.v4.view.ViewPager.addView(ViewPager.java:1479)
        at android.view.ViewGroup.addView(ViewGroup.java:4235)
        at android.view.ViewGroup.addView(ViewGroup.java:4208)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1434)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:797)
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2596)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2383)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338)
        at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:2215)
        at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:649)
        at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:145)
        at android.support.v4.view.ViewPager.populate(ViewPager.java:1238)
        at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:663)
        at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:625)
        at android.support.v4.view.ViewPager.setCurrentItem(ViewPager.java:617)
        at com.laudien.p1xelfehler.x.NonSwipeableViewPager.setCurrentItem(NonSwipeableViewPager.java:31)
        at android.support.design.widget.TabLayout$ViewPagerOnTabSelectedListener.onTabSelected(TabLayout.java:2170)
        at android.support.design.widget.TabLayout.dispatchTabSelected(TabLayout.java:1165)
        at android.support.design.widget.TabLayout.selectTab(TabLayout.java:1158)
        at android.support.design.widget.TabLayout.selectTab(TabLayout.java:1128)
        at android.support.design.widget.TabLayout$Tab.select(TabLayout.java:1427)
        at android.support.design.widget.TabLayout$TabView.performClick(TabLayout.java:1537)
        at android.view.View$PerformClick.run(View.java:22259)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6077)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

### PR DESCRIPTION
**Pull request by oleksandrbalan**
Crash happens when day picker has 30 items but default date is set to date with 31th day.

Fixes #164, #181 and #199.

### CODE REVIEW

**Comment by gowrishgsmove** [comment]
Thanks for the fix!

**Comment by agustinsivoplas** [comment]
This PR will be merged? This is a critical bug.

**Comment by Amaranadh1** [comment]
Shall you provide the complete source code with Today and Tomorrow texts? Thanks In Advance.

**Comment by florent37** [comment]
I merged it

**Pull request merged**
